name: Release

on:
  release:
    types: [published]

permissions:
        contents: write

jobs:
  build-and-release:
    name: Build and Upload
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            original_path: build/scsa
            release_name: scsa-linux
          - os: windows-latest
            original_path: build/Release/scsa.exe
            release_name: scsa-windows.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Prepare Assets
        shell: bash
        run: |
          mkdir -p dist
          cp ${{ matrix.original_path }} dist/${{ matrix.release_name }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.release_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
